[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.23"
tungstenite = "0.23"
futures-util = { version = "0.3", features = ["sink", "std"] }
